window.ieltsData = [
  // SUBLIST 1
  { word: "analyze", sublist: 1, tr: "analiz etmek", en: "To separate into parts in order to determine what something is or how it works.", syn: "examine, study" },
  { word: "approach", sublist: 1, tr: "yaklaşım", en: "A way of dealing with something; a method or strategy.", syn: "method, strategy" },
  { word: "area", sublist: 1, tr: "alan, bölge", en: "A region or part of a town, a country, or the world.", syn: "region, field" },
  { word: "assess", sublist: 1, tr: "değerlendirmek", en: "To evaluate or estimate the nature, ability, or quality of.", syn: "evaluate, judge" },
  { word: "assume", sublist: 1, tr: "varsaymak", en: "To suppose to be the case, without proof.", syn: "presume, suppose" },
  { word: "authority", sublist: 1, tr: "yetki, otorite", en: "The power or right to give orders, make decisions, and enforce obedience.", syn: "power, command" },
  { word: "available", sublist: 1, tr: "mevcut, erişilebilir", en: "Able to be used or obtained; at someone's disposal.", syn: "accessible" },
  { word: "benefit", sublist: 1, tr: "fayda", en: "An advantage or profit gained from something.", syn: "advantage, gain" },
  { word: "concept", sublist: 1, tr: "kavram", en: "An abstract idea; a general notion.", syn: "idea, notion" },
  { word: "consist", sublist: 1, tr: "oluşmak", en: "To be composed or made up of.", syn: "comprise" },
  { word: "constitute", sublist: 1, tr: "oluşturmak", en: "To be (a part) of a whole.", syn: "form, establish" },
  { word: "context", sublist: 1, tr: "bağlam", en: "The circumstances that form the setting for an event, statement, or idea.", syn: "situation" },
  { word: "contract", sublist: 1, tr: "sözleşme", en: "A written or spoken agreement, especially one concerning employment, sales, or tenancy.", syn: "agreement" },
  { word: "create", sublist: 1, tr: "yaratmak", en: "To bring something into existence.", syn: "make, generate" },
  { word: "data", sublist: 1, tr: "veri", en: "Facts and statistics collected together for reference or analysis.", syn: "information" },
  { word: "define", sublist: 1, tr: "tanımlamak", en: "To state or describe exactly the nature, scope, or meaning of something.", syn: "explain, describe" },
  { word: "derive", sublist: 1, tr: "türetmek, kaynaklanmak", en: "To obtain something from a specified source.", syn: "originate, obtain" },
  { word: "distribute", sublist: 1, tr: "dağıtmak", en: "To give shares of something.", syn: "allocate, share" },
  { word: "economy", sublist: 1, tr: "ekonomi", en: "The wealth and resources of a country or region.", syn: "financial system" },
  { word: "environment", sublist: 1, tr: "çevre", en: "The surroundings or conditions in which a person, animal, or plant lives or operates.", syn: "surroundings" },
  { word: "establish", sublist: 1, tr: "kurmak", en: "To set up on a firm or permanent basis.", syn: "set up, found" },
  { word: "estimate", sublist: 1, tr: "tahmin etmek", en: "To roughly calculate or judge the value, number, quantity, or extent of.", syn: "guess, calculate" },
  { word: "evident", sublist: 1, tr: "belirgin", en: "Plain or obvious; clearly seen or understood.", syn: "obvious, clear" },
  { word: "export", sublist: 1, tr: "ihraç etmek", en: "To send goods or services to another country for sale.", syn: "trade abroad" },
  { word: "factor", sublist: 1, tr: "faktör", en: "A circumstance, fact, or influence that contributes to a result or outcome.", syn: "element" },
  { word: "finance", sublist: 1, tr: "finans", en: "The management of large amounts of money.", syn: "funding" },
  { word: "formula", sublist: 1, tr: "formül", en: "A mathematical relationship or rule expressed in symbols.", syn: "equation" },
  { word: "function", sublist: 1, tr: "işlev", en: "An activity or purpose natural to or intended for a person or thing.", syn: "role, purpose" },
  { word: "income", sublist: 1, tr: "gelir", en: "Money received, especially on a regular basis, for work or through investments.", syn: "earnings, revenue" },
  { word: "indicate", sublist: 1, tr: "işaret etmek", en: "To point out; show.", syn: "show, point out" },
  { word: "individual", sublist: 1, tr: "birey", en: "A single human being as distinct from a group, class, or family.", syn: "person" },
  { word: "interpret", sublist: 1, tr: "yorumlamak", en: "To explain the meaning of information, words, or actions.", syn: "explain" },
  { word: "involve", sublist: 1, tr: "içermek, kapsamak", en: "To have or include something as a necessary or integral part or result.", syn: "include, entail" },
  { word: "issue", sublist: 1, tr: "mesele", en: "An important topic or problem for debate or discussion.", syn: "problem, subject" },
  { word: "labor", sublist: 1, tr: "iş gücü", en: "Work, especially hard physical work.", syn: "workforce, work" },
  { word: "legal", sublist: 1, tr: "yasal", en: "Of, based on, or concerned with the law.", syn: "lawful" },
  { word: "legislate", sublist: 1, tr: "yasa yapmak", en: "To make or enact laws.", syn: "make laws" },
  { word: "major", sublist: 1, tr: "başlıca", en: "Important, serious, or significant.", syn: "main, crucial" },
  { word: "method", sublist: 1, tr: "yöntem", en: "A particular form of procedure for accomplishing or approaching something.", syn: "procedure" },
  { word: "occur", sublist: 1, tr: "meydana gelmek", en: "To happen; take place.", syn: "happen" },
  { word: "percent", sublist: 1, tr: "yüzde", en: "By a specified amount in or for every hundred.", syn: "percentage" },
  { word: "period", sublist: 1, tr: "dönem", en: "A length or portion of time.", syn: "time, era" },
  { word: "policy", sublist: 1, tr: "politika, kural", en: "A course or principle of action adopted or proposed by a government, party, business, or individual.", syn: "rule, guideline" },
  { word: "principle", sublist: 1, tr: "ilke", en: "A fundamental truth or proposition that serves as the foundation for a system of belief or behavior.", syn: "rule, standard" },
  { word: "proceed", sublist: 1, tr: "ilerlemek", en: "To begin or continue a course of action.", syn: "continue, advance" },
  { word: "process", sublist: 1, tr: "süreç", en: "A series of actions or steps taken in order to achieve a particular end.", syn: "procedure" },
  { word: "require", sublist: 1, tr: "gerektirmek", en: "Need for a particular purpose.", syn: "need, demand" },
  { word: "research", sublist: 1, tr: "araştırma", en: "The systematic investigation into and study of materials and sources in order to establish facts.", syn: "study, investigation" },
  { word: "respond", sublist: 1, tr: "yanıtlamak", en: "To say something in reply.", syn: "reply, answer" },
  { word: "role", sublist: 1, tr: "rol", en: "The function assumed or part played by a person or thing in a particular situation.", syn: "part, function" },
  { word: "section", sublist: 1, tr: "bölüm", en: "Any of the more or less distinct parts into which something is or may be divided.", syn: "part, segment" },
  { word: "sector", sublist: 1, tr: "sektör", en: "An area or portion that is distinct from others.", syn: "industry, area" },
  { word: "significant", sublist: 1, tr: "önemli", en: "Sufficiently great or important to be worthy of attention.", syn: "important" },
  { word: "similar", sublist: 1, tr: "benzer", en: "Looking or being almost, but not exactly, the same.", syn: "alike" },
  { word: "source", sublist: 1, tr: "kaynak", en: "A place, person, or thing from which something comes or can be obtained.", syn: "origin" },
  { word: "specific", sublist: 1, tr: "belirli", en: "Clearly defined or identified.", syn: "particular" },
  { word: "structure", sublist: 1, tr: "yapı", en: "The arrangement of and relations between the parts or elements of something complex.", syn: "framework" },
  { word: "theory", sublist: 1, tr: "teori", en: "A supposition or a system of ideas intended to explain something.", syn: "hypothesis" },
  { word: "vary", sublist: 1, tr: "değişmek", en: "To differ in size, amount, degree, or nature from something else of the same general class.", syn: "differ, change" },

  // SUBLIST 2
  { word: "achieve", sublist: 2, tr: "başarmak", en: "To successfully bring about or reach a desired objective or result by effort.", syn: "accomplish" },
  { word: "acquire", sublist: 2, tr: "elde etmek", en: "To buy or obtain for oneself.", syn: "obtain, get" },
  { word: "administrate", sublist: 2, tr: "yönetmek", en: "To manage and be responsible for the running of a business, organization, etc.", syn: "manage" },
  { word: "affect", sublist: 2, tr: "etkilemek", en: "To have an effect on; make a difference to.", syn: "influence" },
  { word: "appropriate", sublist: 2, tr: "uygun", en: "Suitable or proper in the circumstances.", syn: "suitable" },
  { word: "aspect", sublist: 2, tr: "yön, açı", en: "A particular part or feature of something.", syn: "feature" },
  { word: "assist", sublist: 2, tr: "yardım etmek", en: "To help someone, typically by doing a share of the work.", syn: "help, aid" },
  { word: "category", sublist: 2, tr: "kategori", en: "A class or division of people or things regarded as having shared characteristics.", syn: "class, group" },
  { word: "chapter", sublist: 2, tr: "bölüm", en: "A main division of a book, typically with a number or title.", syn: "section" },
  { word: "commission", sublist: 2, tr: "komisyon", en: "An instruction, command, or duty given to a person or group of people.", syn: "committee" },
  { word: "community", sublist: 2, tr: "toplum", en: "A group of people living in the same place or having a particular characteristic in common.", syn: "society" },
  { word: "complex", sublist: 2, tr: "karmaşık", en: "Consisting of many different and connected parts.", syn: "complicated" },
  { word: "compute", sublist: 2, tr: "hesaplamak", en: "To calculate or reckon a figure or amount.", syn: "calculate" },
  { word: "conclude", sublist: 2, tr: "sonuçlandırmak", en: "To bring something to an end.", syn: "finish, deduce" },
  { word: "conduct", sublist: 2, tr: "yürütmek", en: "To organize and carry out.", syn: "carry out" },
  { word: "consequent", sublist: 2, tr: "sonuç olan", en: "Following as a result or effect.", syn: "resulting" },
  { word: "construct", sublist: 2, tr: "inşa etmek", en: "To build or erect something, typically a building, road, or machine.", syn: "build" },
  { word: "consume", sublist: 2, tr: "tüketmek", en: "To use up a resource.", syn: "use" },
  { word: "credit", sublist: 2, tr: "itibar, kredi", en: "The ability of a customer to obtain goods or services before payment, based on the trust that payment will be made.", syn: "recognition" },
  { word: "culture", sublist: 2, tr: "kültür", en: "The arts and other manifestations of human intellectual achievement regarded collectively.", syn: "society" },
  { word: "design", sublist: 2, tr: "tasarım", en: "A plan or drawing produced to show the look and function or workings of a building, garment, or other object before it is built or made.", syn: "plan" },
  { word: "distinct", sublist: 2, tr: "farklı, açık", en: "Recognizably different in nature from something else of a similar type.", syn: "clear, separate" },
  { word: "element", sublist: 2, tr: "unsur", en: "A part or aspect of something abstract, especially one that is essential or characteristic.", syn: "component" },
  { word: "equate", sublist: 2, tr: "eşitlemek", en: "To consider one thing to be the same as or equivalent to another.", syn: "balance" },
  { word: "evaluate", sublist: 2, tr: "değerlendirmek", en: "To form an idea of the amount, number, or value of; assess.", syn: "assess" },
  { word: "feature", sublist: 2, tr: "özellik", en: "A distinctive attribute or aspect of something.", syn: "characteristic" },
  { word: "final", sublist: 2, tr: "son", en: "Coming at the end of a series.", syn: "last, ultimate" },
  { word: "focus", sublist: 2, tr: "odaklanmak", en: "To adapt to the prevailing level of light and become able to see clearly.", syn: "concentrate" },
  { word: "impact", sublist: 2, tr: "etki", en: "A marked effect or influence.", syn: "effect" },
  { word: "injure", sublist: 2, tr: "yaralamak", en: "To do physical harm or damage to.", syn: "hurt" },
  { word: "institute", sublist: 2, tr: "kurum", en: "A society or organization having a particular object or common factor, especially a scientific, educational, or social one.", syn: "organization" },
  { word: "invest", sublist: 2, tr: "yatırım yapmak", en: "To expend money with the expectation of achieving a profit or material result.", syn: "fund" },
  { word: "item", sublist: 2, tr: "madde", en: "An individual article or unit, especially one that is part of a list.", syn: "object, thing" },
  { word: "journal", sublist: 2, tr: "dergi", en: "A newspaper or magazine that deals with a particular subject.", syn: "publication" },
  { word: "maintain", sublist: 2, tr: "sürdürmek", en: "To cause or enable to continue.", syn: "keep, preserve" },
  { word: "normal", sublist: 2, tr: "normal", en: "Conforming to a standard; usual, typical, or expected.", syn: "ordinary, typical" },
  { word: "obtain", sublist: 2, tr: "elde etmek", en: "To get, acquire, or secure.", syn: "gain, get" },
  { word: "participate", sublist: 2, tr: "katılmak", en: "To take part in an action or endeavor.", syn: "take part" },
  { word: "perceive", sublist: 2, tr: "algılamak", en: "To become aware or conscious of something; come to realize or understand.", syn: "notice" },
  { word: "positive", sublist: 2, tr: "olumlu", en: "Consisting in or characterized by the presence rather than the absence of distinguishing features.", syn: "optimistic" },
  { word: "potential", sublist: 2, tr: "potansiyel", en: "Having or showing the capacity to become or develop into something in the future.", syn: "possible" },
  { word: "previous", sublist: 2, tr: "önceki", en: "Existing or occurring before in time or order.", syn: "prior" },
  { word: "primary", sublist: 2, tr: "birincil", en: "Of chief importance; principal.", syn: "main" },
  { word: "purchase", sublist: 2, tr: "satın almak", en: "To acquire something by paying for it; buy.", syn: "buy" },
  { word: "range", sublist: 2, tr: "aralık, çeşit", en: "The area of variation between upper and lower limits on a particular scale.", syn: "scope, variety" },
  { word: "region", sublist: 2, tr: "bölge", en: "An area or division, especially part of a country or the world having definable characteristics.", syn: "area" },
  { word: "regulate", sublist: 2, tr: "düzenlemek", en: "To control or maintain the rate or speed of a machine or process.", syn: "control" },
  { word: "relevant", sublist: 2, tr: "ilgili", en: "Closely connected or appropriate to what is being done or considered.", syn: "applicable" },
  { word: "reside", sublist: 2, tr: "ikamet etmek", en: "To live in a particular place.", syn: "live" },
  { word: "resource", sublist: 2, tr: "kaynak", en: "A stock or supply of money, materials, staff, and other assets that can be drawn on by a person or organization.", syn: "supply, asset" },
  { word: "restrict", sublist: 2, tr: "kısıtlamak", en: "To put a limit on; keep under control.", syn: "limit" },
  { word: "secure", sublist: 2, tr: "güvene almak", en: "To protect against threats; make safe.", syn: "safe" },
  { word: "seek", sublist: 2, tr: "aramak", en: "To attempt to find.", syn: "search" },
  { word: "select", sublist: 2, tr: "seçmek", en: "To carefully choose as being the best or most suitable.", syn: "choose" },
  { word: "site", sublist: 2, tr: "alan", en: "An area of ground on which a town, building, or monument is constructed.", syn: "location" },
  { word: "strategy", sublist: 2, tr: "strateji", en: "A plan of action or policy designed to achieve a major or overall aim.", syn: "plan" },
  { word: "survey", sublist: 2, tr: "anket", en: "To look carefully and thoroughly at someone or something.", syn: "review" },
  { word: "text", sublist: 2, tr: "metin", en: "A book or other written or printed work, regarded in terms of its content.", syn: "writing" },
  { word: "tradition", sublist: 2, tr: "gelenek", en: "The transmission of customs or beliefs from generation to generation.", syn: "custom" },
  { word: "transfer", sublist: 2, tr: "transfer", en: "To move from one place to another.", syn: "move" },

  // SUBLIST 3 (A few as an example, database is easily expandable)
  { word: "alternative", sublist: 3, tr: "alternatif", en: "One of two or more available possibilities.", syn: "option" },
  { word: "circumstance", sublist: 3, tr: "durum", en: "A fact or condition connected with or relevant to an event or action.", syn: "situation" },
  { word: "comment", sublist: 3, tr: "yorum", en: "A verbal or written remark expressing an opinion or reaction.", syn: "remark" },
  { word: "component", sublist: 3, tr: "bileşen", en: "A part or element of a larger whole.", syn: "part" },
  { word: "consent", sublist: 3, tr: "onay", en: "Permission for something to happen or agreement to do something.", syn: "agreement" },

  // Diğer listelerden örnekler (Genişletilebilir yapı için örnek 3 kelime)
  { word: "access", sublist: 4, tr: "erişim", en: "The means or opportunity to approach or enter a place.", syn: "entry" },
  { word: "capacity", sublist: 5, tr: "kapasite", en: "The maximum amount that something can contain.", syn: "volume" },
  { word: "abstract", sublist: 6, tr: "soyut", en: "Existing in thought or as an idea but not having a physical or concrete existence.", syn: "theoretical" }
];
