window.ieltsData = [
{word:"analyze",sublist:1,tr:"analiz etmek",en:"Examine methodically",syn:"examine"},
{word:"approach",sublist:1,tr:"yaklaşım",en:"A way of dealing with something",syn:"method"},
{word:"area",sublist:1,tr:"alan",en:"A region or part of a town",syn:"region"},
{word:"assess",sublist:1,tr:"değerlendirmek",en:"Evaluate or estimate",syn:"evaluate"},
{word:"assume",sublist:1,tr:"varsaymak",en:"Suppose to be the case",syn:"presume"},
{word:"authority",sublist:1,tr:"otorite",en:"The power to give orders",syn:"power"},
{word:"available",sublist:1,tr:"mevcut",en:"Able to be used",syn:"accessible"},
{word:"benefit",sublist:1,tr:"fayda",en:"An advantage or profit",syn:"advantage"},
{word:"concept",sublist:1,tr:"kavram",en:"An abstract idea",syn:"idea"},
{word:"consist",sublist:1,tr:"oluşmak",en:"Be composed or made up of",syn:"comprise"},
{word:"constitute",sublist:1,tr:"oluşturmak",en:"Be a part of a whole",syn:"form"},
{word:"context",sublist:1,tr:"bağlam",en:"The circumstances that form the setting",syn:"situation"},
{word:"contract",sublist:1,tr:"sözleşme",en:"A written or spoken agreement",syn:"agreement"},
{word:"create",sublist:1,tr:"yaratmak",en:"Bring something into existence",syn:"make"},
{word:"data",sublist:1,tr:"veri",en:"Facts and statistics",syn:"information"},
{word:"define",sublist:1,tr:"tanımlamak",en:"State or describe exactly",syn:"explain"},
{word:"derive",sublist:1,tr:"türetmek",en:"Obtain something from a specified source",syn:"originate"},
{word:"distribute",sublist:1,tr:"dağıtmak",en:"Give shares of something",syn:"allocate"},
{word:"economy",sublist:1,tr:"ekonomi",en:"Wealth and resources of a country",syn:"financial system"},
{word:"environment",sublist:1,tr:"çevre",en:"The surroundings or conditions",syn:"surroundings"},
{word:"establish",sublist:1,tr:"kurmak",en:"Set up on a firm basis",syn:"set up"},
{word:"estimate",sublist:1,tr:"tahmin etmek",en:"Roughly calculate or judge",syn:"guess"},
{word:"evident",sublist:1,tr:"belirgin",en:"Plain or obvious",syn:"clear"},
{word:"export",sublist:1,tr:"ihraç etmek",en:"Send goods to another country",syn:"trade abroad"},
{word:"factor",sublist:1,tr:"faktör",en:"A circumstance, fact, or influence",syn:"element"},
{word:"finance",sublist:1,tr:"finans",en:"Management of large amounts of money",syn:"funding"},
{word:"formula",sublist:1,tr:"formül",en:"A mathematical relationship",syn:"equation"},
{word:"function",sublist:1,tr:"işlev",en:"An activity or purpose",syn:"role"},
{word:"income",sublist:1,tr:"gelir",en:"Money received",syn:"earnings"},
{word:"indicate",sublist:1,tr:"göstermek",en:"Point out; show",syn:"show"},
{word:"individual",sublist:1,tr:"birey",en:"A single human being",syn:"person"},
{word:"interpret",sublist:1,tr:"yorumlamak",en:"Explain the meaning of",syn:"explain"},
{word:"involve",sublist:1,tr:"içermek",en:"Include something as necessary",syn:"include"},
{word:"issue",sublist:1,tr:"mesele",en:"An important topic or problem",syn:"problem"},
{word:"labor",sublist:1,tr:"iş gücü",en:"Work, hard physical work",syn:"workforce"},
{word:"legal",sublist:1,tr:"yasal",en:"Appointed or required by the law",syn:"lawful"},
{word:"legislate",sublist:1,tr:"yasa yapmak",en:"Make or enact laws",syn:"make laws"},
{word:"major",sublist:1,tr:"başlıca",en:"Important, serious, or significant",syn:"main"},
{word:"method",sublist:1,tr:"yöntem",en:"A particular form of procedure",syn:"procedure"},
{word:"occur",sublist:1,tr:"meydana gelmek",en:"Happen; take place",syn:"happen"},
{word:"percent",sublist:1,tr:"yüzde",en:"By a specified amount in every hundred",syn:"percentage"},
{word:"period",sublist:1,tr:"dönem",en:"A length or portion of time",syn:"time"},
{word:"policy",sublist:1,tr:"politika",en:"A course or principle of action",syn:"rule"},
{word:"principle",sublist:1,tr:"ilke",en:"A fundamental truth or proposition",syn:"standard"},
{word:"proceed",sublist:1,tr:"ilerlemek",en:"Begin or continue a course of action",syn:"advance"},
{word:"process",sublist:1,tr:"süreç",en:"A series of actions or steps",syn:"procedure"},
{word:"require",sublist:1,tr:"gerektirmek",en:"Need for a particular purpose",syn:"demand"},
{word:"research",sublist:1,tr:"araştırma",en:"The systematic investigation",syn:"study"},
{word:"respond",sublist:1,tr:"yanıtlamak",en:"Say something in reply",syn:"reply"},
{word:"role",sublist:1,tr:"rol",en:"The function assumed",syn:"part"},
{word:"section",sublist:1,tr:"bölüm",en:"More or less distinct parts",syn:"part"},
{word:"sector",sublist:1,tr:"sektör",en:"An area or portion",syn:"area"},
{word:"significant",sublist:1,tr:"önemli",en:"Sufficiently great or important",syn:"important"},
{word:"similar",sublist:1,tr:"benzer",en:"Looking or being almost the same",syn:"alike"},
{word:"source",sublist:1,tr:"kaynak",en:"A place from which something comes",syn:"origin"},
{word:"specific",sublist:1,tr:"belirli",en:"Clearly defined or identified",syn:"particular"},
{word:"structure",sublist:1,tr:"yapı",en:"The arrangement of parts",syn:"framework"},
{word:"theory",sublist:1,tr:"teori",en:"A supposition or a system of ideas",syn:"hypothesis"},
{word:"vary",sublist:1,tr:"değişmek",en:"Differ in size, amount, degree",syn:"differ"},
{word:"achieve",sublist:2,tr:"başarmak",en:"Successfully bring about",syn:"accomplish"},
{word:"acquire",sublist:2,tr:"elde etmek",en:"Buy or obtain for oneself",syn:"obtain"},
{word:"administrate",sublist:2,tr:"yönetmek",en:"Manage and be responsible for",syn:"manage"},
{word:"affect",sublist:2,tr:"etkilemek",en:"Have an effect on",syn:"influence"},
{word:"appropriate",sublist:2,tr:"uygun",en:"Suitable or proper",syn:"suitable"},
{word:"aspect",sublist:2,tr:"yön",en:"A particular part or feature",syn:"feature"},
{word:"assist",sublist:2,tr:"yardım etmek",en:"Help someone",syn:"help"},
{word:"category",sublist:2,tr:"kategori",en:"A class or division of people or things",syn:"class"},
{word:"chapter",sublist:2,tr:"bölüm",en:"A main division of a book",syn:"section"},
{word:"commission",sublist:2,tr:"komisyon",en:"An instruction, command, or duty",syn:"committee"},
{word:"community",sublist:2,tr:"toplum",en:"A group of people living together",syn:"society"},
{word:"complex",sublist:2,tr:"karmaşık",en:"Consisting of many different parts",syn:"complicated"},
{word:"compute",sublist:2,tr:"hesaplamak",en:"Calculate or reckon",syn:"calculate"},
{word:"conclude",sublist:2,tr:"sonuçlandırmak",en:"Bring something to an end",syn:"finish"},
{word:"conduct",sublist:2,tr:"yürütmek",en:"Organize and carry out",syn:"carry out"},
{word:"consequent",sublist:2,tr:"sonuç olan",en:"Following as a result",syn:"resulting"},
{word:"construct",sublist:2,tr:"inşa etmek",en:"Build or erect something",syn:"build"},
{word:"consume",sublist:2,tr:"tüketmek",en:"Use up a resource",syn:"use"},
{word:"credit",sublist:2,tr:"itibar",en:"Public acknowledgment or praise",syn:"recognition"},
{word:"culture",sublist:2,tr:"kültür",en:"Arts and other manifestations of human intellect",syn:"society"},
{word:"design",sublist:2,tr:"tasarım",en:"A plan or drawing produced",syn:"plan"},
{word:"distinct",sublist:2,tr:"farklı",en:"Recognizably different in nature",syn:"clear"},
{word:"element",sublist:2,tr:"unsur",en:"A part or aspect of something abstract",syn:"component"},
{word:"equate",sublist:2,tr:"eşitlemek",en:"Consider one thing to be the same as another",syn:"balance"},
{word:"evaluate",sublist:2,tr:"değerlendirmek",en:"Form an idea of the value",syn:"assess"},
{word:"feature",sublist:2,tr:"özellik",en:"A distinctive attribute or aspect",syn:"characteristic"},
{word:"final",sublist:2,tr:"son",en:"Coming at the end of a series",syn:"last"},
{word:"focus",sublist:2,tr:"odaklanmak",en:"Pay particular attention to",syn:"concentrate"},
{word:"impact",sublist:2,tr:"etki",en:"A marked effect or influence",syn:"effect"},
{word:"injure",sublist:2,tr:"yaralamak",en:"Do physical harm or damage",syn:"hurt"},
{word:"institute",sublist:2,tr:"kurum",en:"A society or organization",syn:"organization"},
{word:"invest",sublist:2,tr:"yatırım yapmak",en:"Expend money with the expectation of achieving a profit",syn:"fund"},
{word:"item",sublist:2,tr:"madde",en:"An individual article or unit",syn:"object"},
{word:"journal",sublist:2,tr:"dergi",en:"A newspaper or magazine",syn:"publication"},
{word:"maintain",sublist:2,tr:"sürdürmek",en:"Cause or enable to continue",syn:"preserve"},
{word:"normal",sublist:2,tr:"normal",en:"Conforming to a standard",syn:"ordinary"},
{word:"obtain",sublist:2,tr:"elde etmek",en:"Get, acquire, or secure",syn:"gain"},
{word:"participate",sublist:2,tr:"katılmak",en:"Take part",syn:"take part"},
{word:"perceive",sublist:2,tr:"algılamak",en:"Become aware or conscious of",syn:"notice"},
{word:"positive",sublist:2,tr:"olumlu",en:"Constructive, optimistic",syn:"optimistic"},
{word:"potential",sublist:2,tr:"potansiyel",en:"Having or showing the capacity",syn:"possible"},
{word:"previous",sublist:2,tr:"önceki",en:"Existing or occurring before",syn:"prior"},
{word:"primary",sublist:2,tr:"birincil",en:"Of chief importance",syn:"main"},
{word:"purchase",sublist:2,tr:"satın almak",en:"Acquire something by paying",syn:"buy"},
{word:"range",sublist:2,tr:"çeşitlilik",en:"The area of variation",syn:"scope"},
{word:"region",sublist:2,tr:"bölge",en:"An area or division",syn:"area"},
{word:"regulate",sublist:2,tr:"düzenlemek",en:"Control or maintain",syn:"control"},
{word:"relevant",sublist:2,tr:"ilgili",en:"Closely connected",syn:"applicable"},
{word:"reside",sublist:2,tr:"ikamet etmek",en:"Live in a particular place",syn:"live"},
{word:"resource",sublist:2,tr:"kaynak",en:"A stock or supply of money/materials",syn:"supply"},
{word:"restrict",sublist:2,tr:"kısıtlamak",en:"Put a limit on",syn:"limit"},
{word:"secure",sublist:2,tr:"güvene almak",en:"Protect against threats",syn:"safe"},
{word:"seek",sublist:2,tr:"aramak",en:"Attempt to find",syn:"search"},
{word:"select",sublist:2,tr:"seçmek",en:"Carefully choose",syn:"choose"},
{word:"site",sublist:2,tr:"alan",en:"An area of ground",syn:"location"},
{word:"strategy",sublist:2,tr:"strateji",en:"A plan of action",syn:"plan"},
{word:"survey",sublist:2,tr:"anket",en:"Look carefully and thoroughly",syn:"review"},
{word:"text",sublist:2,tr:"metin",en:"A book or other written work",syn:"writing"},
{word:"tradition",sublist:2,tr:"gelenek",en:"Transmission of customs",syn:"custom"},
{word:"transfer",sublist:2,tr:"aktarmak",en:"Move from one place to another",syn:"move"},
{word:"alternative",sublist:3,tr:"alternatif",en:"One of two or more possibilities",syn:"option"},
{word:"circumstance",sublist:3,tr:"durum",en:"A fact or condition",syn:"situation"},
{word:"comment",sublist:3,tr:"yorum",en:"A verbal or written remark",syn:"remark"},
{word:"compensate",sublist:3,tr:"telafi etmek",en:"Give someone something to make up for loss",syn:"make up for"},
{word:"component",sublist:3,tr:"bileşen",en:"A part or element",syn:"part"},
{word:"consent",sublist:3,tr:"rıza",en:"Permission for something to happen",syn:"agreement"},
{word:"considerable",sublist:3,tr:"önemli ölçüde",en:"Notably large in size",syn:"significant"},
{word:"constant",sublist:3,tr:"sabit",en:"Occurring continuously",syn:"steady"},
{word:"constrain",sublist:3,tr:"zorlamak",en:"Compel or force",syn:"restrict"},
{word:"contribute",sublist:3,tr:"katkıda bulunmak",en:"Give in order to help achieve",syn:"add"},
{word:"convene",sublist:3,tr:"toplanmak",en:"Come or bring together",syn:"gather"},
{word:"coordinate",sublist:3,tr:"koordine etmek",en:"Bring the different elements into relationship",syn:"organize"},
{word:"core",sublist:3,tr:"çekirdek",en:"The tough central part",syn:"center"},
{word:"corporate",sublist:3,tr:"kurumsal",en:"Relating to a corporation",syn:"business"},
{word:"correspond",sublist:3,tr:"tekabül etmek",en:"Have a close similarity",syn:"match"},
{word:"criteria",sublist:3,tr:"kriter",en:"A principle or standard",syn:"standard"},
{word:"deduce",sublist:3,tr:"çıkarım yapmak",en:"Arrive at a fact by reasoning",syn:"infer"},
{word:"demonstrate",sublist:3,tr:"göstermek",en:"Clearly show the existence or truth",syn:"show"},
{word:"document",sublist:3,tr:"belge",en:"A piece of written matter",syn:"record"},
{word:"dominate",sublist:3,tr:"hakim olmak",en:"Have a commanding influence",syn:"control"},
{word:"emphasis",sublist:3,tr:"vurgu",en:"Special importance",syn:"stress"},
{word:"ensure",sublist:3,tr:"garanti etmek",en:"Make certain that something shall occur",syn:"secure"},
{word:"exclude",sublist:3,tr:"hariç tutmak",en:"Deny someone access",syn:"omit"},
{word:"framework",sublist:3,tr:"çerçeve",en:"An essential supporting structure",syn:"structure"},
{word:"fund",sublist:3,tr:"fon",en:"A sum of money saved",syn:"capital"},
{word:"illustrate",sublist:3,tr:"örneklemek",en:"Explain by using examples",syn:"explain"},
{word:"immigrate",sublist:3,tr:"göçmek",en:"Come to live permanently in a foreign country",syn:"migrate"},
{word:"imply",sublist:3,tr:"ima etmek",en:"Strongly suggest the truth",syn:"suggest"},
{word:"initial",sublist:3,tr:"ilk",en:"Existing or occurring at the beginning",syn:"first"},
{word:"instance",sublist:3,tr:"örnek",en:"An example or single occurrence",syn:"example"},
{word:"interact",sublist:3,tr:"etkileşimde bulunmak",en:"Act in such a way as to have an effect",syn:"communicate"},
{word:"justify",sublist:3,tr:"haklı çıkarmak",en:"Show or prove to be right",syn:"validate"},
{word:"layer",sublist:3,tr:"katman",en:"A sheet, quantity, or thickness",syn:"level"},
{word:"link",sublist:3,tr:"bağlantı",en:"A relationship between two things",syn:"connection"},
{word:"locate",sublist:3,tr:"yerini saptamak",en:"Discover the exact place",syn:"find"},
{word:"maximize",sublist:3,tr:"maksimize etmek",en:"Make as large or great as possible",syn:"increase"},
{word:"minor",sublist:3,tr:"önemsiz",en:"Lesser in importance",syn:"small"},
{word:"negate",sublist:3,tr:"yalanlamak",en:"Nullify; make ineffective",syn:"cancel"},
{word:"outcome",sublist:3,tr:"sonuç",en:"The way a thing turns out",syn:"result"},
{word:"partner",sublist:3,tr:"ortak",en:"A person who takes part in an undertaking",syn:"companion"},
{word:"philosophy",sublist:3,tr:"felsefe",en:"The study of the fundamental nature of knowledge",syn:"ideology"},
{word:"physical",sublist:3,tr:"fiziksel",en:"Relating to the body",syn:"tangible"},
{word:"proportion",sublist:3,tr:"oran",en:"A part in comparative relation to a whole",syn:"ratio"},
{word:"publish",sublist:3,tr:"yayınlamak",en:"Prepare and issue for public sale",syn:"print"},
{word:"react",sublist:3,tr:"tepki vermek",en:"Respond or behave in a particular way",syn:"respond"},
{word:"register",sublist:3,tr:"kaydetmek",en:"Enter or record on an official list",syn:"enroll"},
{word:"rely",sublist:3,tr:"güvenmek",en:"Depend on with full trust",syn:"depend"},
{word:"remove",sublist:3,tr:"kaldırmak",en:"Take something away from its position",syn:"eliminate"},
{word:"scheme",sublist:3,tr:"tasarı",en:"A large-scale systematic plan",syn:"plan"},
{word:"sequence",sublist:3,tr:"sıra",en:"A particular order in which related events follow",syn:"order"},
{word:"sex",sublist:3,tr:"cinsiyet",en:"Either of the two main categories (male/female)",syn:"gender"},
{word:"shift",sublist:3,tr:"değişim",en:"A slight change in position, direction",syn:"change"},
{word:"specify",sublist:3,tr:"belirlemek",en:"Identify clearly and definitely",syn:"define"},
{word:"sufficient",sublist:3,tr:"yeterli",en:"Enough; adequate",syn:"adequate"},
{word:"task",sublist:3,tr:"görev",en:"A piece of work to be done",syn:"job"},
{word:"technical",sublist:3,tr:"teknik",en:"Relating to a particular subject or art",syn:"mechanical"},
{word:"technique",sublist:3,tr:"teknik",en:"A way of carrying out a particular task",syn:"method"},
{word:"technology",sublist:3,tr:"teknoloji",en:"The application of scientific knowledge",syn:"equipment"},
{word:"valid",sublist:3,tr:"geçerli",en:"Having a sound basis in logic or fact",syn:"authentic"},
{word:"volume",sublist:3,tr:"hacim",en:"The amount of space that a substance occupies",syn:"capacity"},
{word:"access",sublist:4,tr:"erişim",en:"The means of approaching or entering",syn:"entry"},
{word:"adequate",sublist:4,tr:"yeterli",en:"Satisfactory or acceptable in quality",syn:"sufficient"},
{word:"annual",sublist:4,tr:"yıllık",en:"Occurring once a year",syn:"yearly"},
{word:"apparent",sublist:4,tr:"belirgin",en:"Clearly visible or understood",syn:"obvious"},
{word:"approximate",sublist:4,tr:"yaklaşık",en:"Close to the actual, but not completely accurate",syn:"rough"},
{word:"attitude",sublist:4,tr:"tutum",en:"A settled way of thinking",syn:"mindset"},
{word:"attribute",sublist:4,tr:"atfetmek",en:"Regard something as being caused by",syn:"characteristic"},
{word:"civil",sublist:4,tr:"sivil",en:"Relating to ordinary citizens",syn:"domestic"},
{word:"code",sublist:4,tr:"kod",en:"A system of words, letters, figures",syn:"rules"},
{word:"commit",sublist:4,tr:"kalkışmak",en:"Carry out or perpetrate",syn:"dedicate"},
{word:"communicate",sublist:4,tr:"iletişim kurmak",en:"Share or exchange information",syn:"convey"},
{word:"concentrate",sublist:4,tr:"odaklanmak",en:"Focus one's attention",syn:"focus"},
{word:"confer",sublist:4,tr:"danışmak",en:"Grant or bestow; have discussions",syn:"consult"},
{word:"contrast",sublist:4,tr:"zıtlık",en:"The state of being strikingly different",syn:"difference"},
{word:"cycle",sublist:4,tr:"döngü",en:"A series of events that are regularly repeated",syn:"loop"},
{word:"debate",sublist:4,tr:"tartışma",en:"A formal discussion on a particular topic",syn:"argument"},
{word:"despite",sublist:4,tr:"rağmen",en:"Without being affected by",syn:"in spite of"},
{word:"dimension",sublist:4,tr:"boyut",en:"A measurable extent of some kind",syn:"size"},
{word:"domestic",sublist:4,tr:"yerel",en:"Existing or occurring inside a particular country",syn:"local"},
{word:"emerge",sublist:4,tr:"ortaya çıkmak",en:"Move out of or away from something",syn:"arise"},
{word:"error",sublist:4,tr:"hata",en:"A mistake",syn:"mistake"},
{word:"ethnic",sublist:4,tr:"etnik",en:"Relating to a population subgroup",syn:"cultural"},
{word:"goal",sublist:4,tr:"hedef",en:"The object of a person's ambition",syn:"aim"},
{word:"grant",sublist:4,tr:"hibe",en:"Agree to give or allow",syn:"award"},
{word:"hence",sublist:4,tr:"bu yüzden",en:"As a consequence; for this reason",syn:"therefore"},
{word:"hypothesis",sublist:4,tr:"hipotez",en:"A supposition or proposed explanation",syn:"theory"},
{word:"implement",sublist:4,tr:"uygulamak",en:"Put a decision, plan into effect",syn:"apply"},
{word:"implicate",sublist:4,tr:"bulaştırmak",en:"Show to be involved in a crime",syn:"involve"},
{word:"impose",sublist:4,tr:"dayatmak",en:"Force to be accepted or put in place",syn:"force"},
{word:"integrate",sublist:4,tr:"entegre etmek",en:"Combine one thing with another",syn:"combine"},
{word:"internal",sublist:4,tr:"iç",en:"Of or situated on the inside",syn:"inside"},
{word:"investigate",sublist:4,tr:"araştırmak",en:"Carry out a systematic or formal inquiry",syn:"examine"},
{word:"job",sublist:4,tr:"iş",en:"A paid position of regular employment",syn:"occupation"},
{word:"label",sublist:4,tr:"etiket",en:"A small piece of paper attached to an object",syn:"tag"},
{word:"mechanism",sublist:4,tr:"mekanizma",en:"A system of parts working together",syn:"system"},
{word:"obvious",sublist:4,tr:"bariz",en:"Easily perceived or understood",syn:"clear"},
{word:"occupy",sublist:4,tr:"işgal etmek",en:"Take control of a place",syn:"inhabit"},
{word:"option",sublist:4,tr:"seçenek",en:"A thing that is or may be chosen",syn:"choice"},
{word:"output",sublist:4,tr:"çıktı",en:"The amount of something produced",syn:"yield"},
{word:"overall",sublist:4,tr:"genel",en:"Taken as a whole; in all",syn:"general"},
{word:"parallel",sublist:4,tr:"paralel",en:"Occurring or existing at the same time",syn:"similar"},
{word:"parameter",sublist:4,tr:"parametre",en:"A limit or boundary",syn:"limit"},
{word:"phase",sublist:4,tr:"evre",en:"A distinct period or stage",syn:"stage"},
{word:"predict",sublist:4,tr:"tahmin etmek",en:"Say or estimate that a specified thing will happen",syn:"forecast"},
{word:"principal",sublist:4,tr:"ana",en:"First in order of importance",syn:"main"},
{word:"prior",sublist:4,tr:"önce",en:"Existing or coming before",syn:"previous"},
{word:"professional",sublist:4,tr:"profesyonel",en:"Relating to or connected with a profession",syn:"expert"},
{word:"project",sublist:4,tr:"proje",en:"An individual or collaborative enterprise",syn:"task"},
{word:"promote",sublist:4,tr:"teşvik etmek",en:"Advance or raise to a higher position",syn:"encourage"},
{word:"regime",sublist:4,tr:"rejim",en:"A government, especially an authoritarian one",syn:"system"},
{word:"resolve",sublist:4,tr:"çözmek",en:"Settle or find a solution to",syn:"fix"},
{word:"retain",sublist:4,tr:"muhafaza etmek",en:"Continue to have something",syn:"keep"},
{word:"series",sublist:4,tr:"dizi",en:"A number of events coming one after another",syn:"chain"},
{word:"statistic",sublist:4,tr:"istatistik",en:"A fact or piece of data",syn:"data"},
{word:"status",sublist:4,tr:"statü",en:"The relative social or professional position",syn:"rank"},
{word:"stress",sublist:4,tr:"vurgulamak",en:"Give particular emphasis",syn:"emphasize"},
{word:"subsequent",sublist:4,tr:"sonraki",en:"Coming after something in time",syn:"following"},
{word:"sum",sublist:4,tr:"toplam",en:"A particular amount of money",syn:"total"},
{word:"summary",sublist:4,tr:"özet",en:"A brief statement",syn:"overview"},
{word:"undertake",sublist:4,tr:"üstlenmek",en:"Commit oneself to and begin",syn:"take on"},
{word:"academy",sublist:5,tr:"akademi",en:"A place of study or training",syn:"institution"},
{word:"adjust",sublist:5,tr:"ayarlamak",en:"Alter slightly in order to achieve the desired result",syn:"tune"},
{word:"alter",sublist:5,tr:"değiştirmek",en:"Change or cause to change in character",syn:"change"},
{word:"amend",sublist:5,tr:"düzeltmek",en:"Make minor changes",syn:"revise"},
{word:"aware",sublist:5,tr:"farkında",en:"Having knowledge or perception of a situation",syn:"conscious"},
{word:"capacity",sublist:5,tr:"kapasite",en:"The maximum amount that something can contain",syn:"volume"},
{word:"challenge",sublist:5,tr:"zorluk",en:"A call to take part in a contest or competition",syn:"test"},
{word:"clause",sublist:5,tr:"madde",en:"A particular and separate article",syn:"condition"},
{word:"compound",sublist:5,tr:"bileşik",en:"A thing that is composed of two or more separate elements",syn:"mixture"},
{word:"conflict",sublist:5,tr:"çatışma",en:"A serious disagreement or argument",syn:"dispute"},
{word:"consult",sublist:5,tr:"danışmak",en:"Seek information or advice from",syn:"ask"},
{word:"contact",sublist:5,tr:"bağlantı",en:"The state or condition of physical touching",syn:"touch"},
{word:"decline",sublist:5,tr:"azalmak",en:"Become smaller, fewer, or less",syn:"reduce"},
{word:"discrete",sublist:5,tr:"ayrı",en:"Individually separate and distinct",syn:"separate"},
{word:"draft",sublist:5,tr:"taslak",en:"A preliminary version of a piece of writing",syn:"outline"},
{word:"enable",sublist:5,tr:"olanak tanımak",en:"Give someone the authority or means to do something",syn:"allow"},
{word:"energy",sublist:5,tr:"enerji",en:"The strength and vitality required for sustained activity",syn:"strength"},
{word:"enforce",sublist:5,tr:"uygulamak",en:"Compel observance of",syn:"impose"},
{word:"entity",sublist:5,tr:"varlık",en:"A thing with distinct and independent existence",syn:"being"},
{word:"equivalent",sublist:5,tr:"eşdeğer",en:"Equal in value, amount, function",syn:"equal"},
{word:"evolve",sublist:5,tr:"gelişmek",en:"Develop gradually",syn:"develop"},
{word:"expand",sublist:5,tr:"genişlemek",en:"Become or make larger",syn:"grow"},
{word:"expose",sublist:5,tr:"maruz bırakmak",en:"Make something visible",syn:"reveal"},
{word:"external",sublist:5,tr:"dış",en:"Belonging to or forming the outer surface",syn:"outside"},
{word:"facilitate",sublist:5,tr:"kolaylaştırmak",en:"Make an action or process easy",syn:"ease"},
{word:"fundamental",sublist:5,tr:"temel",en:"Forming a necessary base or core",syn:"basic"},
{word:"generate",sublist:5,tr:"üretmek",en:"Cause to arise or come about",syn:"create"},
{word:"generation",sublist:5,tr:"nesil",en:"All of the people born at about the same time",syn:"age group"},
{word:"image",sublist:5,tr:"görüntü",en:"A representation of the external form of a person or thing",syn:"picture"},
{word:"liberal",sublist:5,tr:"özgür",en:"Open to new behavior or opinions",syn:"tolerant"},
{word:"license",sublist:5,tr:"izin",en:"A permit from an authority",syn:"permit"},
{word:"logic",sublist:5,tr:"mantık",en:"Reasoning conducted or assessed",syn:"sense"},
{word:"margin",sublist:5,tr:"kenar",en:"The edge or border of something",syn:"border"},
{word:"medical",sublist:5,tr:"tıbbi",en:"Relating to the science of medicine",syn:"clinical"},
{word:"mental",sublist:5,tr:"zihinsel",en:"Relating to the mind",syn:"cognitive"},
{word:"modify",sublist:5,tr:"değiştirmek",en:"Make partial or minor changes to",syn:"alter"},
{word:"monitor",sublist:5,tr:"izlemek",en:"Observe and check the progress",syn:"observe"},
{word:"network",sublist:5,tr:"ağ",en:"A group or system of interconnected people or things",syn:"web"},
{word:"notion",sublist:5,tr:"fikir",en:"A conception of or belief about something",syn:"idea"},
{word:"objective",sublist:5,tr:"nesnel",en:"Not influenced by personal feelings",syn:"goal"},
{word:"orient",sublist:5,tr:"yönlendirmek",en:"Align or position",syn:"align"},
{word:"perspective",sublist:5,tr:"bakış açısı",en:"A point of view",syn:"viewpoint"},
{word:"precise",sublist:5,tr:"kesin",en:"Marked by exactness",syn:"exact"},
{word:"prime",sublist:5,tr:"asıl",en:"Of first importance",syn:"main"},
{word:"psychology",sublist:5,tr:"psikoloji",en:"The scientific study of the human mind",syn:"mind study"},
{word:"pursue",sublist:5,tr:"takip etmek",en:"Follow someone or something",syn:"follow"},
{word:"ratio",sublist:5,tr:"oran",en:"The quantitative relation between two amounts",syn:"proportion"},
{word:"reject",sublist:5,tr:"reddetmek",en:"Dismiss as inadequate",syn:"deny"},
{word:"revenue",sublist:5,tr:"gelir",en:"Income, especially when of a company or organization",syn:"income"},
{word:"stable",sublist:5,tr:"istikrarlı",en:"Not likely to change",syn:"steady"},
{word:"style",sublist:5,tr:"tarz",en:"A manner of doing something",syn:"manner"},
{word:"substitute",sublist:5,tr:"yerine geçmek",en:"Use or add in place of",syn:"replace"},
{word:"sustain",sublist:5,tr:"sürdürmek",en:"Strengthen or support",syn:"maintain"},
{word:"symbol",sublist:5,tr:"sembol",en:"A mark or character used as a conventional representation",syn:"sign"},
{word:"target",sublist:5,tr:"hedef",en:"A person, object, or place selected as the aim",syn:"goal"},
{word:"transit",sublist:5,tr:"geçiş",en:"The carrying of people or things",syn:"transport"},
{word:"trend",sublist:5,tr:"eğilim",en:"A general direction in which something is developing",syn:"tendency"},
{word:"version",sublist:5,tr:"versiyon",en:"A particular form of something",syn:"variant"},
{word:"welfare",sublist:5,tr:"refah",en:"The health, happiness, and fortunes of a person",syn:"wellbeing"},
{word:"whereas",sublist:5,tr:"oysa",en:"In contrast or comparison",syn:"while"},
{word:"abstract",sublist:6,tr:"soyut",en:"Existing in thought",syn:"theoretical"},
{word:"accurate",sublist:6,tr:"kesin",en:"Correct in all details",syn:"correct"},
{word:"acknowledge",sublist:6,tr:"kabul etmek",en:"Accept or admit the existence",syn:"admit"},
{word:"assign",sublist:6,tr:"atamak",en:"Allocate a job",syn:"allocate"},
{word:"attach",sublist:6,tr:"eklemek",en:"Fasten; join",syn:"join"},
{word:"author",sublist:6,tr:"yazar",en:"A writer of a book",syn:"writer"},
{word:"bond",sublist:6,tr:"bağ",en:"A relationship between people",syn:"connection"},
{word:"brief",sublist:6,tr:"kısa",en:"Of short duration",syn:"short"},
{word:"capable",sublist:6,tr:"yetenekli",en:"Having the ability",syn:"able"},
{word:"cite",sublist:6,tr:"alıntılamak",en:"Quote as evidence",syn:"quote"},
{word:"cooperate",sublist:6,tr:"işbirliği",en:"Work jointly",syn:"work together"},
{word:"discriminate",sublist:6,tr:"ayrım yapmak",en:"Make an unjust distinction",syn:"treat unfairly"},
{word:"display",sublist:6,tr:"göstermek",en:"Make a prominent exhibition",syn:"show"},
{word:"diverse",sublist:6,tr:"çeşitli",en:"Showing a great deal of variety",syn:"varied"},
{word:"domain",sublist:6,tr:"alan",en:"An area of territory",syn:"realm"},
{word:"edit",sublist:6,tr:"düzenlemek",en:"Prepare for publication",syn:"revise"},
{word:"enhance",sublist:6,tr:"iyileştirmek",en:"Intensify, increase",syn:"improve"},
{word:"estate",sublist:6,tr:"mülk",en:"An extensive area of land",syn:"property"},
{word:"exceed",sublist:6,tr:"aşmak",en:"Be greater in number",syn:"surpass"},
{word:"expert",sublist:6,tr:"uzman",en:"A person who has a comprehensive skill",syn:"specialist"},
{word:"explicit",sublist:6,tr:"açık",en:"Stated clearly",syn:"clear"},
{word:"federal",sublist:6,tr:"federal",en:"Relating to a central government",syn:"national"},
{word:"fee",sublist:6,tr:"ücret",en:"A payment made to a professional",syn:"cost"},
{word:"flexible",sublist:6,tr:"esnek",en:"Capable of bending easily",syn:"adaptable"},
{word:"furthermore",sublist:6,tr:"dahası",en:"In addition",syn:"moreover"},
{word:"gender",sublist:6,tr:"cinsiyet",en:"Either of the two sexes",syn:"sex"},
{word:"ignorant",sublist:6,tr:"cahil",en:"Lacking knowledge",syn:"uneducated"},
{word:"incentive",sublist:6,tr:"teşvik",en:"A thing that motivates",syn:"motivation"},
{word:"incidence",sublist:6,tr:"sıklık",en:"The occurrence",syn:"occurrence"},
{word:"incorporate",sublist:6,tr:"dahil etmek",en:"Take in or contain",syn:"include"},
{word:"index",sublist:6,tr:"endeks",en:"An alphabetical list",syn:"list"},
{word:"inhibit",sublist:6,tr:"engellemek",en:"Hinder, restrain",syn:"hold back"},
{word:"initiate",sublist:6,tr:"başlatmak",en:"Cause to begin",syn:"start"},
{word:"input",sublist:6,tr:"girdi",en:"What is put in",syn:"data"},
{word:"instruct",sublist:6,tr:"talimat vermek",en:"Direct or command",syn:"teach"},
{word:"intelligence",sublist:6,tr:"zeka",en:"The ability to acquire knowledge",syn:"smarts"},
{word:"interval",sublist:6,tr:"aralık",en:"An intervening time",syn:"gap"},
{word:"lecture",sublist:6,tr:"ders",en:"An educational talk",syn:"talk"},
{word:"migrate",sublist:6,tr:"göçmek",en:"Move from one region to another",syn:"move"},
{word:"minimum",sublist:6,tr:"en az",en:"The smallest amount",syn:"lowest"},
{word:"ministry",sublist:6,tr:"bakanlık",en:"A government department",syn:"department"},
{word:"motive",sublist:6,tr:"güdü",en:"A reason for doing something",syn:"reason"},
{word:"neutral",sublist:6,tr:"tarafsız",en:"Not helping or supporting either side",syn:"impartial"},
{word:"nevertheless",sublist:6,tr:"yine de",en:"In spite of that",syn:"however"},
{word:"overseas",sublist:6,tr:"denizaşırı",en:"In or to a foreign country",syn:"abroad"},
{word:"precede",sublist:6,tr:"önce gelmek",en:"Come before in time",syn:"come before"},
{word:"presume",sublist:6,tr:"farz etmek",en:"Suppose that something is the case",syn:"assume"},
{word:"rational",sublist:6,tr:"mantıklı",en:"Based on or in accordance with reason",syn:"logical"},
{word:"recover",sublist:6,tr:"iyileşmek",en:"Return to a normal state",syn:"get better"},
{word:"reveal",sublist:6,tr:"ortaya çıkarmak",en:"Make known",syn:"disclose"},
{word:"scope",sublist:6,tr:"kapsam",en:"The extent of the area",syn:"range"},
{word:"subsidy",sublist:6,tr:"mali destek",en:"A sum of money granted",syn:"grant"},
{word:"tape",sublist:6,tr:"bant",en:"A narrow strip of material",syn:"record"},
{word:"trace",sublist:6,tr:"iz",en:"A mark, object, or other indication",syn:"track"},
{word:"transform",sublist:6,tr:"dönüştürmek",en:"Make a thorough or dramatic change",syn:"change"},
{word:"transport",sublist:6,tr:"taşıma",en:"Take or carry from one place to another",syn:"carry"},
{word:"underlie",sublist:6,tr:"altında yatmak",en:"Be the cause or basis of",syn:"basis"},
{word:"utilize",sublist:6,tr:"kullanmak",en:"Make practical and effective use of",syn:"use"},
{word:"adapt",sublist:7,tr:"uyum sağlamak",en:"Make suitable for a new use",syn:"adjust"},
{word:"adult",sublist:7,tr:"yetişkin",en:"A person who is fully grown",syn:"grown-up"},
{word:"advocate",sublist:7,tr:"desteklemek",en:"Publicly recommend or support",syn:"support"},
{word:"aid",sublist:7,tr:"yardım",en:"Help, typically of a practical nature",syn:"help"},
{word:"channel",sublist:7,tr:"kanal",en:"A length of water joining two larger areas",syn:"route"},
{word:"chemical",sublist:7,tr:"kimyasal",en:"A distinct compound or substance",syn:"substance"},
{word:"classic",sublist:7,tr:"klasik",en:"Judged over a period of time to be of the highest quality",syn:"traditional"},
{word:"comprehensive",sublist:7,tr:"kapsamlı",en:"Complete; including all or nearly all elements",syn:"thorough"},
{word:"comprise",sublist:7,tr:"içermek",en:"Consist of; be made up of",syn:"consist of"},
{word:"confirm",sublist:7,tr:"doğrulamak",en:"Establish the truth or correctness of",syn:"verify"},
{word:"contrary",sublist:7,tr:"ters",en:"Opposite in nature, direction, or meaning",syn:"opposite"},
{word:"convert",sublist:7,tr:"dönüştürmek",en:"Cause to change in form, character, or function",syn:"alter"},
{word:"couple",sublist:7,tr:"çift",en:"Two individuals of the same sort",syn:"pair"},
{word:"decade",sublist:7,tr:"on yıl",en:"A period of ten years",syn:"ten years"},
{word:"definite",sublist:7,tr:"kesin",en:"Clearly stated or decided",syn:"clear"},
{word:"deny",sublist:7,tr:"inkar etmek",en:"State that one refuses to admit the truth",syn:"refuse"},
{word:"differentiate",sublist:7,tr:"ayırmak",en:"Recognize or ascertain what makes someone or something different",syn:"distinguish"},
{word:"dispose",sublist:7,tr:"elden çıkarmak",en:"Get rid of by throwing away",syn:"get rid of"},
{word:"dynamic",sublist:7,tr:"hareketli",en:"Characterized by constant change",syn:"active"},
{word:"eliminate",sublist:7,tr:"bertaraf etmek",en:"Completely remove or get rid of",syn:"remove"},
{word:"empirical",sublist:7,tr:"deneysel",en:"Based on, concerned with",syn:"observed"},
{word:"equip",sublist:7,tr:"donatmak",en:"Supply with the necessary items",syn:"provide"},
{word:"extract",sublist:7,tr:"çıkarmak",en:"Remove or take out",syn:"remove"},
{word:"file",sublist:7,tr:"dosya",en:"A folder or box for holding loose papers",syn:"document"},
{word:"finite",sublist:7,tr:"sonlu",en:"Having limits or bounds",syn:"limited"},
{word:"foundation",sublist:7,tr:"temel",en:"The lowest load-bearing part of a building",syn:"base"},
{word:"globe",sublist:7,tr:"yerküre",en:"The earth",syn:"world"},
{word:"grade",sublist:7,tr:"derece",en:"A particular level of rank, quality, proficiency",syn:"level"},
{word:"guarantee",sublist:7,tr:"garanti",en:"A formal promise or assurance",syn:"promise"},
{word:"hierarchy",sublist:7,tr:"hiyerarşi",en:"A system or organization in which people or groups are ranked one above the other",syn:"ranking"},
{word:"identical",sublist:7,tr:"aynı",en:"Similar in every detail",syn:"exact"},
{word:"ideology",sublist:7,tr:"ideoloji",en:"A system of ideas and ideals",syn:"beliefs"},
{word:"infer",sublist:7,tr:"çıkarım yapmak",en:"Deduce or conclude from evidence",syn:"deduce"},
{word:"innovate",sublist:7,tr:"yenilik yapmak",en:"Make changes in something established",syn:"invent"},
{word:"insert",sublist:7,tr:"eklemek",en:"Place, fit, or thrust something into another thing",syn:"put in"},
{word:"intervene",sublist:7,tr:"araya girmek",en:"Come between so as to prevent",syn:"interfere"},
{word:"isolate",sublist:7,tr:"yalıtmak",en:"Cause a person or place to be or remain alone",syn:"separate"},
{word:"media",sublist:7,tr:"medya",en:"The main means of mass communication",syn:"press"},
{word:"mode",sublist:7,tr:"tarz",en:"A way or manner in which something occurs or is experienced",syn:"way"},
{word:"paradigm",sublist:7,tr:"model",en:"A typical example or pattern of something",syn:"model"},
{word:"phenomenon",sublist:7,tr:"fenomen",en:"A fact or situation that is observed to exist or happen",syn:"occurrence"},
{word:"priority",sublist:7,tr:"öncelik",en:"The fact or condition of being regarded or treated as more important",syn:"importance"},
{word:"prohibit",sublist:7,tr:"yasaklamak",en:"Formally forbid something by law",syn:"ban"},
{word:"publication",sublist:7,tr:"yayın",en:"The preparation and issuing of a book",syn:"publishing"},
{word:"quote",sublist:7,tr:"alıntı",en:"Repeat or copy out",syn:"cite"},
{word:"release",sublist:7,tr:"serbest bırakmak",en:"Allow or enable to escape",syn:"free"},
{word:"reverse",sublist:7,tr:"ters",en:"Move backward",syn:"backward"},
{word:"simulate",sublist:7,tr:"taklit etmek",en:"Imitate the appearance or character of",syn:"imitate"},
{word:"sole",sublist:7,tr:"tek",en:"One and only",syn:"only"},
{word:"somewhat",sublist:7,tr:"biraz",en:"To a moderate extent or by a moderate amount",syn:"partially"},
{word:"submit",sublist:7,tr:"teslim etmek",en:"Accept or yield to a superior force",syn:"present"},
{word:"successor",sublist:7,tr:"halef",en:"A person or thing that succeeds another",syn:"heir"},
{word:"survive",sublist:7,tr:"hayatta kalmak",en:"Continue to live or exist",syn:"live on"},
{word:"suspend",sublist:7,tr:"askıya almak",en:"Temporarily prevent from continuing",syn:"delay"},
{word:"thesis",sublist:7,tr:"tez",en:"A statement or theory that is put forward as a premise",syn:"argument"},
{word:"topic",sublist:7,tr:"konu",en:"A matter dealt with in a text or conversation",syn:"subject"},
{word:"transmit",sublist:7,tr:"iletmek",en:"Cause something to pass on from one place to another",syn:"send"},
{word:"ultimate",sublist:7,tr:"nihai",en:"Being or happening at the end of a process",syn:"final"},
{word:"unique",sublist:7,tr:"eşsiz",en:"Being the only one of its kind",syn:"rare"},
{word:"voluntary",sublist:7,tr:"gönüllü",en:"Done, given, or acting of one's own free will",syn:"willing"},
{word:"abandon",sublist:8,tr:"terk etmek",en:"Cease to support or look after",syn:"leave"},
{word:"accompany",sublist:8,tr:"eşlik etmek",en:"Go somewhere with someone",syn:"go with"},
{word:"accumulate",sublist:8,tr:"biriktirmek",en:"Gather together or acquire an increasing number",syn:"collect"},
{word:"ambiguous",sublist:8,tr:"belirsiz",en:"Open to more than one interpretation",syn:"unclear"},
{word:"append",sublist:8,tr:"eklemek",en:"Add as an attachment or supplement",syn:"attach"},
{word:"appreciate",sublist:8,tr:"takdir etmek",en:"Recognize the full worth of",syn:"value"},
{word:"arbitrary",sublist:8,tr:"keyfi",en:"Based on random choice or personal whim",syn:"random"},
{word:"automate",sublist:8,tr:"otomatikleştirmek",en:"Convert to largely automatic operation",syn:"mechanize"},
{word:"bias",sublist:8,tr:"ön yargı",en:"Prejudice in favor of or against one thing",syn:"prejudice"},
{word:"chart",sublist:8,tr:"grafik",en:"A sheet of information in the form of a table or graph",syn:"graph"},
{word:"clarify",sublist:8,tr:"netleştirmek",en:"Make a statement or situation less confused",syn:"explain"},
{word:"commodity",sublist:8,tr:"mal",en:"A raw material or primary agricultural product",syn:"goods"},
{word:"complement",sublist:8,tr:"tamamlayıcı",en:"A thing that completes or brings to perfection",syn:"complete"},
{word:"conform",sublist:8,tr:"uymak",en:"Comply with rules, standards, or laws",syn:"comply"},
{word:"contemporary",sublist:8,tr:"çağdaş",en:"Living or occurring at the same time",syn:"modern"},
{word:"contradict",sublist:8,tr:"çelişmek",en:"Deny the truth of a statement",syn:"oppose"},
{word:"crucial",sublist:8,tr:"çok önemli",en:"Decisive or critical",syn:"vital"},
{word:"currency",sublist:8,tr:"para birimi",en:"A system of money in general use",syn:"money"},
{word:"denote",sublist:8,tr:"ifade etmek",en:"Be a sign of; indicate",syn:"signify"},
{word:"detect",sublist:8,tr:"saptamak",en:"Discover or identify the presence or existence of",syn:"find"},
{word:"deviate",sublist:8,tr:"sapmak",en:"Depart from an established course",syn:"wander"},
{word:"displace",sublist:8,tr:"yerinden etmek",en:"Take over the place, position, or role of",syn:"move"},
{word:"drama",sublist:8,tr:"drama",en:"A play for theater",syn:"play"},
{word:"eventual",sublist:8,tr:"sonuç olan",en:"Occurring at the end of or as a result of a series",syn:"final"},
{word:"exhibit",sublist:8,tr:"sergilemek",en:"Publicly display",syn:"show"},
{word:"exploit",sublist:8,tr:"faydalanmak",en:"Make full use of and derive benefit from",syn:"use"},
{word:"fluctuate",sublist:8,tr:"dalgalanmak",en:"Rise and fall irregularly in number or amount",syn:"vary"},
{word:"guideline",sublist:8,tr:"yönerge",en:"A general rule, principle, or piece of advice",syn:"rule"},
{word:"highlight",sublist:8,tr:"vurgulamak",en:"Pick out and emphasize",syn:"underline"},
{word:"implicit",sublist:8,tr:"üstü kapalı",en:"Implied though not plainly expressed",syn:"implied"},
{word:"induce",sublist:8,tr:"neden olmak",en:"Succeed in persuading or influencing",syn:"cause"},
{word:"inevitable",sublist:8,tr:"kaçınılmaz",en:"Certain to happen; unavoidable",syn:"unavoidable"},
{word:"infrastructure",sublist:8,tr:"altyapı",en:"The basic physical and organizational structures",syn:"framework"},
{word:"inspect",sublist:8,tr:"denetlemek",en:"Look at someone or something closely",syn:"examine"},
{word:"intense",sublist:8,tr:"şiddetli",en:"Of extreme force, degree, or strength",syn:"extreme"},
{word:"manipulate",sublist:8,tr:"yönlendirmek",en:"Handle or control typically in a skillful manner",syn:"handle"},
{word:"minimize",sublist:8,tr:"asgariye indirmek",en:"Reduce to the smallest possible amount",syn:"reduce"},
{word:"nuclear",sublist:8,tr:"nükleer",en:"Relating to the nucleus of an atom",syn:"atomic"},
{word:"offset",sublist:8,tr:"dengelemek",en:"Counteract by having an opposing force or effect",syn:"balance"},
{word:"paragraph",sublist:8,tr:"paragraf",en:"A distinct section of a piece of writing",syn:"section"},
{word:"plus",sublist:8,tr:"artı",en:"With the addition of",syn:"addition"},
{word:"practitioner",sublist:8,tr:"pratisyen",en:"A person actively engaged in an art, discipline",syn:"professional"},
{word:"predominant",sublist:8,tr:"baskın",en:"Present as the strongest or main element",syn:"main"},
{word:"prospect",sublist:8,tr:"olasılık",en:"The possibility or likelihood of some future event occurring",syn:"possibility"},
{word:"radical",sublist:8,tr:"radikal",en:"Relating to or affecting the fundamental nature of something",syn:"extreme"},
{word:"random",sublist:8,tr:"rastgele",en:"Made, done, happening, or chosen without method",syn:"chance"},
{word:"reinforce",sublist:8,tr:"güçlendirmek",en:"Strengthen or support, especially with additional personnel or material",syn:"support"},
{word:"restore",sublist:8,tr:"eski haline getirmek",en:"Bring back",syn:"renew"},
{word:"revise",sublist:8,tr:"gözden geçirmek",en:"Re-examine and make alterations to",syn:"alter"},
{word:"schedule",sublist:8,tr:"program",en:"A plan for carrying out a process or procedure",syn:"plan"},
{word:"tense",sublist:8,tr:"gergin",en:"Stretched tight or rigid",syn:"anxious"},
{word:"terminate",sublist:8,tr:"son vermek",en:"Bring to an end",syn:"end"},
{word:"theme",sublist:8,tr:"tema",en:"The subject of a talk, a piece of writing",syn:"subject"},
{word:"thereby",sublist:8,tr:"böylece",en:"By that means; as a result of that",syn:"thus"},
{word:"uniform",sublist:8,tr:"standart",en:"Not changing in form or character",syn:"consistent"},
{word:"vehicle",sublist:8,tr:"araç",en:"A thing used for transporting people or goods",syn:"transport"},
{word:"via",sublist:8,tr:"vasıtasıyla",en:"Traveling through a place en route to a destination",syn:"by means of"},
{word:"virtual",sublist:8,tr:"sanal",en:"Almost or nearly as described",syn:"simulated"},
{word:"visual",sublist:8,tr:"görsel",en:"Relating to seeing or sight",syn:"graphic"},
{word:"widespread",sublist:8,tr:"yaygın",en:"Found or distributed over a large area",syn:"extensive"},
{word:"accommodate",sublist:9,tr:"barındırmak",en:"Provide lodging or sufficient space for",syn:"house"},
{word:"analogy",sublist:9,tr:"benzerlik",en:"A comparison between two things",syn:"comparison"},
{word:"anticipate",sublist:9,tr:"ön görmek",en:"Regard as probable",syn:"expect"},
{word:"assure",sublist:9,tr:"güvence vermek",en:"Tell someone something positively to dispel any doubts",syn:"guarantee"},
{word:"attain",sublist:9,tr:"başarmak",en:"Succeed in achieving",syn:"reach"},
{word:"behalf",sublist:9,tr:"adına",en:"In the interests of a person, group, or principle",syn:"in place of"},
{word:"bulk",sublist:9,tr:"büyük kısım",en:"The mass or magnitude of something large",syn:"mass"},
{word:"cease",sublist:9,tr:"durmak",en:"Bring or come to an end",syn:"stop"},
{word:"coherent",sublist:9,tr:"tutarlı",en:"Logical and consistent",syn:"logical"},
{word:"coincide",sublist:9,tr:"rastlamak",en:"Occur at or during the same time",syn:"occur together"},
{word:"commence",sublist:9,tr:"başlamak",en:"Begin; start",syn:"begin"},
{word:"compatible",sublist:9,tr:"uyumlu",en:"Able to exist or occur together without conflict",syn:"well-matched"},
{word:"concurrent",sublist:9,tr:"eş zamanlı",en:"Existing, happening, or done at the same time",syn:"simultaneous"},
{word:"confine",sublist:9,tr:"sınırlandırmak",en:"Keep or restrict someone or something within certain limits",syn:"restrict"},
{word:"controversy",sublist:9,tr:"tartışma",en:"Disagreement, typically when prolonged, public, and heated",syn:"debate"},
{word:"converse",sublist:9,tr:"sohbet etmek",en:"Engage in conversation",syn:"opposite"},
{word:"device",sublist:9,tr:"aygıt",en:"A thing made or adapted for a particular purpose",syn:"gadget"},
{word:"devote",sublist:9,tr:"adamak",en:"Give all or a large part of one's time or resources",syn:"dedicate"},
{word:"diminish",sublist:9,tr:"azalmak",en:"Make or become less",syn:"decrease"},
{word:"distort",sublist:9,tr:"saptırmak",en:"Pull or twist out of shape",syn:"falsify"},
{word:"duration",sublist:9,tr:"süre",en:"The time during which something continues",syn:"length"},
{word:"erode",sublist:9,tr:"aşındırmak",en:"Gradually wear away",syn:"wear away"},
{word:"ethic",sublist:9,tr:"ahlak",en:"A set of moral principles",syn:"moral"},
{word:"format",sublist:9,tr:"format",en:"The way in which something is arranged or set out",syn:"layout"},
{word:"founded",sublist:9,tr:"kurulmuş",en:"Having a basis",syn:"established"},
{word:"inherent",sublist:9,tr:"doğasında olan",en:"Existing in something as a permanent, essential, or characteristic attribute",syn:"built-in"},
{word:"insight",sublist:9,tr:"içgörü",en:"The capacity to gain an accurate and deep intuitive understanding",syn:"understanding"},
{word:"integral",sublist:9,tr:"gerekli",en:"Necessary to make a whole complete",syn:"essential"},
{word:"intermediate",sublist:9,tr:"orta seviye",en:"Coming between two things in time, place, order",syn:"middle"},
{word:"manual",sublist:9,tr:"kılavuz",en:"Relating to or done with the hands",syn:"handbook"},
{word:"mature",sublist:9,tr:"olgun",en:"Fully developed physically; full-grown",syn:"fully grown"},
{word:"mediate",sublist:9,tr:"ara bulmak",en:"Intervene between people in a dispute in order to bring about an agreement",syn:"negotiate"},
{word:"medium",sublist:9,tr:"ortam",en:"An agency or means of doing something",syn:"method"},
{word:"military",sublist:9,tr:"askeri",en:"Relating to or characteristic of soldiers or armed forces",syn:"armed"},
{word:"minimal",sublist:9,tr:"asgari",en:"Of a minimum amount, quantity",syn:"least"},
{word:"mutual",sublist:9,tr:"karşılıklı",en:"Held in common by two or more parties",syn:"shared"},
{word:"norm",sublist:9,tr:"kural",en:"Something that is usual, typical, or standard",syn:"standard"},
{word:"overlap",sublist:9,tr:"örtüşmek",en:"Extend over so as to cover partly",syn:"cover"},
{word:"passive",sublist:9,tr:"edilgen",en:"Accepting or allowing what happens",syn:"inactive"},
{word:"portion",sublist:9,tr:"kısım",en:"A part of a whole",syn:"part"},
{word:"preliminary",sublist:9,tr:"ön",en:"Denoting an action or event preceding or done in preparation for something fuller or more important",syn:"initial"},
{word:"protocol",sublist:9,tr:"protokol",en:"The official procedure or system of rules governing affairs of state or diplomatic occasions",syn:"procedure"},
{word:"qualitative",sublist:9,tr:"nitelikli",en:"Relating to, measuring, or measured by the quality of something rather than its quantity",syn:"subjective"},
{word:"refine",sublist:9,tr:"geliştirmek",en:"Improve by making small changes",syn:"improve"},
{word:"relax",sublist:9,tr:"rahatlamak",en:"Make or become less tense",syn:"calm"},
{word:"restrain",sublist:9,tr:"dizginlemek",en:"Prevent from doing something",syn:"hold back"},
{word:"revolution",sublist:9,tr:"devrim",en:"A forcible overthrow of a government or social order in favor of a new system",syn:"rebellion"},
{word:"rigid",sublist:9,tr:"katı",en:"Unable to bend or be forced out of shape",syn:"strict"},
{word:"route",sublist:9,tr:"rota",en:"A way or course taken in getting from a starting point to a destination",syn:"path"},
{word:"scenario",sublist:9,tr:"senaryo",en:"A written outline of a movie, novel, or stage work giving details of the plot and individual scenes",syn:"situation"},
{word:"sphere",sublist:9,tr:"alan",en:"An area of activity, interest, or expertise",syn:"area"},
{word:"subordinate",sublist:9,tr:"alt makam",en:"Lower in rank or position",syn:"lower"},
{word:"supplement",sublist:9,tr:"takviye",en:"Something that completes or enhances something else when added to it",syn:"addition"},
{word:"suspend",sublist:9,tr:"askıya almak",en:"Temporarily prevent from continuing or being in force or effect",syn:"halt"},
{word:"team",sublist:9,tr:"takım",en:"A group of players forming one side in a competitive game or sport",syn:"group"},
{word:"temporary",sublist:9,tr:"geçici",en:"Lasting for only a limited period of time; not permanent",syn:"brief"},
{word:"trigger",sublist:9,tr:"tetiklemek",en:"Cause to happen or exist",syn:"spark"},
{word:"unify",sublist:9,tr:"birleştirmek",en:"Make or become united, uniform, or whole",syn:"unite"},
{word:"violate",sublist:9,tr:"ihlal etmek",en:"Break or fail to comply with",syn:"break"},
{word:"vision",sublist:9,tr:"vizyon",en:"The faculty or state of being able to see",syn:"sight"},
{word:"adjacent",sublist:10,tr:"bitişik",en:"Next to or adjoining something else",syn:"next"},
{word:"albeit",sublist:10,tr:"rağmen",en:"Although",syn:"although"},
{word:"assemble",sublist:10,tr:"bir araya getirmek",en:"Gather together in one place for a common purpose",syn:"gather"},
{word:"collapse",sublist:10,tr:"çökmek",en:"Fall down or in",syn:"fall down"},
{word:"colleague",sublist:10,tr:"iş arkadaşı",en:"A person with whom one works",syn:"co-worker"},
{word:"compile",sublist:10,tr:"derlemek",en:"Produce something by assembling information",syn:"gather"},
{word:"conceive",sublist:10,tr:"tasarlamak",en:"Form or devise a plan or idea",syn:"think"},
{word:"convince",sublist:10,tr:"ikna etmek",en:"Cause someone to believe firmly in the truth of something",syn:"persuade"},
{word:"depress",sublist:10,tr:"moral bozmak",en:"Make someone feel utterly dispirited or dejected",syn:"sadden"},
{word:"encounter",sublist:10,tr:"rastlamak",en:"Unexpectedly experience or be faced with",syn:"meet"},
{word:"enormous",sublist:10,tr:"devasa",en:"Very large in size, quantity, or extent",syn:"huge"},
{word:"forthcoming",sublist:10,tr:"gelecek olan",en:"Planned for or about to happen in the near future",syn:"upcoming"},
{word:"incline",sublist:10,tr:"eğilim göstermek",en:"Feel willing or favorably disposed toward",syn:"lean"},
{word:"integrity",sublist:10,tr:"dürüstlük",en:"The quality of being honest and having strong moral principles",syn:"honesty"},
{word:"intrinsic",sublist:10,tr:"içsel",en:"Belonging naturally",syn:"essential"},
{word:"invoke",sublist:10,tr:"başvurmak",en:"Cite or appeal to",syn:"appeal"},
{word:"levy",sublist:10,tr:"vergi salmak",en:"Impose",syn:"tax"},
{word:"likewise",sublist:10,tr:"keza",en:"In the same way",syn:"similarly"},
{word:"nonetheless",sublist:10,tr:"her şeye rağmen",en:"In spite of that",syn:"nevertheless"},
{word:"notwithstanding",sublist:10,tr:"rağmen",en:"In spite of",syn:"despite"},
{word:"odd",sublist:10,tr:"tuhaf",en:"Different from what is usual or expected",syn:"strange"},
{word:"ongoing",sublist:10,tr:"devam eden",en:"Continuing; still in progress",syn:"continuing"},
{word:"panel",sublist:10,tr:"jüri",en:"A small group of people brought together to investigate or decide",syn:"board"},
{word:"persist",sublist:10,tr:"ısrar etmek",en:"Continue firmly or obstinately",syn:"continue"},
{word:"pose",sublist:10,tr:"ortaya koymak",en:"Present or constitute",syn:"present"},
{word:"reluctance",sublist:10,tr:"isteksizlik",en:"Unwillingness or disinclination to do something",syn:"unwillingness"},
{word:"so-called",sublist:10,tr:"sözde",en:"Used to show that something or someone is commonly designated by the name or term specified",syn:"supposed"},
{word:"straightforward",sublist:10,tr:"anlaşılır",en:"Uncomplicated and easy to do or understand",syn:"direct"},
{word:"undergo",sublist:10,tr:"maruz kalmak",en:"Experience or be subjected to typically something unpleasant",syn:"experience"},
{word:"whereby",sublist:10,tr:"aracılığı ile",en:"By which",syn:"by which"}
];
